name: gem-release
on:
#  push:
#    branches: [master]
    workflow_dispatch
#  pull_request:
#    branches:
#      - master
jobs:
  deploy-MRI-gem:
    runs-on: ubuntu-16.04
    env:
      RUBYGEMS_API_KEY: 'something'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3
          bundler-cache: true
      - run: echo 'run deploy gem cmd'
  deploy-JRuby-gem:
    runs-on: ubuntu-16.04
    env:
      RUBYGEMS_API_KEY: 'something'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3
          bundler-cache: true
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: |
          echo -e "---\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          bundle exec rake gem:release
        shell: bash
