name: gem-smoke-test
on:
#  push:
#    branches: [master]
    workflow_dispatch
#  pull_request:
#    branches:
#      - master
jobs:
  gem-smoke-test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby-version: [2.3, jruby-9.1.17]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3
          bundler-cache: true
      - uses: actions/setup-java@v2
        if: ${{ matrix.ruby-version == 'jruby-9.1.17' }}
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: |
          gem install gooddata
          ruby -e "require 'gooddata';GoodData.version"