name: Post-merge
on:
  workflow_dispatch
#  schedule:
#    # UTC Time
#    - cron: '30 5 * * *'
jobs:
  lcm-integration-tests:
    runs-on: ubuntu-16.04
    env:
      vcr_on: false
      ruby-version: jruby-9.1.17
    strategy:
      matrix:
        include:
          - gd_env: staging
          - gd_env: testing
          - gd_env: development
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
          bundler-cache: true
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: run tests
        run: |
          bundle exec rake -f lcm.rake docker:build
          bundle exec rake -f lcm.rake docker:bundle
          bundle exec rake -f lcm.rake test:docker:integration
        env:
          VCR_ON: ${{ env.vcr_on }}
          GD_ENV: ${{ matrix.gd_env }}
#        continue-on-error: true
##go
#  lcm-slow-tests:
#    runs-on: ubuntu-16.04
#    env:
#      vcr_on: false
#      ruby-version: jruby-9.1.17
#    strategy:
#      matrix:
#        include:
#          - gd_env: staging
#          - gd_env: testing
#          - gd_env: development
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: ${{ env.ruby-version }}
#          bundler-cache: true
#      - uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#      - name: run tests
#        run: |
#          sudo keytool -importcert -alias gooddata-2008 -file "./data/2008.crt" -keystore $JAVA_HOME/jre/lib/security/cacerts -trustcacerts -storepass 'changeit' -noprompt
#          sudo keytool -importcert -alias gooddata-int -file "./data/new_ca.cer" -keystore $JAVA_HOME/jre/lib/security/cacerts -trustcacerts -storepass 'changeit' -noprompt
#          sudo keytool -importcert -alias gooddata-prod -file "data/new_prodgdc_ca.crt" -keystore $JAVA_HOME/jre/lib/security/cacerts -trustcacerts -storepass 'changeit' -noprompt
#          bundle exec rake -f lcm.rake test:slow
#        env:
#          VCR_ON: ${{ env.vcr_on }}
#          GD_ENV: ${{ matrix.gd_env }}
#        continue-on-error: true
#  bricks-smoke-tests:
#    runs-on: ubuntu-16.04
#    env:
#      vcr_on: false
#      ruby-version: jruby-9.1.17
#    strategy:
#      matrix:
#        include:
#          - gd_env: staging
#          - gd_env: testing
#          - gd_env: development
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: ${{ env.ruby-version }}
#          bundler-cache: true
#      - uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#      - name: run tests
#        run: |
#          bundle exec rake -f lcm.rake docker:build
#          bundle exec rake -f lcm.rake docker:bundle
#          bundle exec rake -f lcm.rake test:docker:integration
#        env:
#          VCR_ON: ${{ env.vcr_on }}
#          GD_ENV: ${{ matrix.gd_env }}
#        continue-on-error: true
