name: Pre merge pipeline
on:
#  push:
#    branches: [master]
  pull_request:
    branches: [master]
jobs:
  uni-tests:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby-version: [2.3, 2.4, 2.5, 2.6, jruby-9.1.14]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test:unit
  sdk-integration-tests:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby-version: [2.3]
    env:
      VCR_RECORD_MODE: none
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test:sdk
      - run: bundle exec rake test:project
  lcm-integration-tests:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby-version: [2.3]
    env:
      VCR_RECORD_MODE: none
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rspec spec/lcm/integration/lcm_end_to_end_spec.rb
